$(document).ready(function () {

// Setting up the datePicker languages
	$.datepicker.regional = {
		"ar": {
			closeText: "إغلاق",
			prevText: "السابق",
			nextText: "التالي",
			currentText: "اليوم",
			monthNames: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو",
				"يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
			monthNamesShort: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
			dayNames: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
			dayNamesShort: ["أحد", "اثنين", "ثلاثاء", "أربعاء", "خميس", "جمعة", "سبت"],
			dayNamesMin: ["ح", "ن", "ث", "ر", "خ", "ج", "س"],
			weekHeader: "أسبوع",
//				dateFormat: "dd/mm/yy",
			dateFormat: "yy-mm-dd",
			firstDay: 0,
			isRTL: true,
			showMonthAfterYear: false,
			yearSuffix: ""
		},
		"de": {
			closeText: "Schließen",
			prevText: "Zurück",
			nextText: "Vor",
			currentText: "Heute",
			monthNames: ["Januar", "Februar", "März", "April", "Mai", "Juni",
				"Juli", "August", "September", "Oktober", "November", "Dezember"],
			monthNamesShort: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun",
				"Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
			dayNames: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
			dayNamesShort: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
			dayNamesMin: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
			weekHeader: "KW",
//				dateFormat: "dd.mm.yy",
			dateFormat: "yy-mm-dd",
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ""
		},
		"es": {
			closeText: "Cerrar",
			prevText: "Ant",
			nextText: "Sig",
			currentText: "Hoy",
			monthNames: ["enero", "febrero", "marzo", "abril", "mayo", "junio",
				"julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
			monthNamesShort: ["ene", "feb", "mar", "abr", "may", "jun",
				"jul", "ago", "sep", "oct", "nov", "dic"],
			dayNames: ["domingo", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado"],
			dayNamesShort: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"],
			dayNamesMin: ["D", "L", "M", "X", "J", "V", "S"],
			weekHeader: "Sm",
//				dateFormat: "dd/mm/yy",
			dateFormat: "yy-mm-dd",
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ""
		},
		"fr": {
			closeText: "Fermer",
			prevText: "Précédent",
			nextText: "Suivant",
			currentText: "Aujourd'hui",
			monthNames: ["janvier", "février", "mars", "avril", "mai", "juin",
				"juillet", "août", "septembre", "octobre", "novembre", "décembre"],
			monthNamesShort: ["janv.", "févr.", "mars", "avr.", "mai", "juin",
				"juil.", "août", "sept.", "oct.", "nov.", "déc."],
			dayNames: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
			dayNamesShort: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
			dayNamesMin: ["D", "L", "M", "M", "J", "V", "S"],
			weekHeader: "Sem.",
//				dateFormat: "dd/mm/yy",
			dateFormat: "yy-mm-dd",
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ""
		},
		"en": {
			closeText: "Done",
			prevText: "Prev",
			nextText: "Next",
			currentText: "Today",
			monthNames: ["January", "February", "March", "April", "May", "June",
				"July", "August", "September", "October", "November", "December"],
			monthNamesShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
				"Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
			dayNames: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
			dayNamesShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
			dayNamesMin: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
			weekHeader: "Wk",
//				dateFormat: "dd/mm/yy",
			dateFormat: "yy-mm-dd",
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ""
		}
	};

// Setting up the default locale
	$.datepicker.setDefaults($.datepicker.regional[locale]);
});